### ISSUE TITLE
CreateAccountAsync() does not permit first_name, last_name

### ISSUE THREAD

**Issue by cpaul747** [recurly/recurly-client-dotnet#402] opened 2019-05-24 16:16 UTC
**Describe the bug**

Following the readme to do a simple account creation causes the api to complain about the first_name and last_name fields:

`Validation: Please remove the following unpermitted parameters from your request: first_name, last_name.
`
**To Reproduce**

Steps to reproduce the behavior.
```
(model.Address populated via .NET Model Binding)
            var accountRequest = new AccountCreate()
            {
                Code = "TEST001",
                FirstName = model.Address.FirstName,
                LastName = model.Address.LastName,
                Address = model.Address,
                TaxExempt = false
            };
            var account = await client.CreateAccountAsync(accountRequest);
```

**Expected behavior**

Account should be created.

**Your Environment**

- Which version of this library are you using?
3.0.0-beta.3

- Which version of dotnet are you using?
.NET Core 2.2

**Comment by bhelx** [comment] 2019-05-24 16:32
@cpaul747 thanks for the detailed report! I can't seem to repro with the sync call. Gonna try the async call. What is the model.Address object?

**Comment by bhelx** [comment] 2019-05-24 17:25
@cpaul747 I was able to repro with the account:

```csharp
                var accountReq = new AccountCreate()
                {
                    Code = accountCode,
                    FirstName = "First",
                    LastName = "Last",,
                    Address = new Address()
                    {
                        FirstName="First",
                        LastName="Last",
                        //...
                    }
                };
                Account account = client.CreateAccount(accountReq);
```

The issue is in the address. I'll take a look at fixing this for the next release. If you want to get past this for the time being, I suggest Not setting the first and last name on the address.

**Comment by cpaul747** [comment] 2019-05-28 18:02
Thanks, I'm just evaluating the platform so the fixes aren't time critical for me.  Thanks for the workaround in the meanwhile.

**Comment by bhelx** [comment] 2020-03-22 20:38
Closing as this should be fixed. Please re-open if you are still getting an exception on the latest version of the clkient.

**Closed by bhelx** 2020-03-22 20:38 UTC
Labels: V3, bug
