### ISSUE TITLE
The 'PreviousInvoiceId' field always null

### ISSUE THREAD

**Issue by oktaras** [recurly/recurly-client-dotnet#464] opened 2019-11-22 16:33 UTC
When I was working with version 2, I often used the "[OriginalInvoiceNumber](https://github.com/recurly/recurly-client-net/blob/v2/Library/Invoice.cs#L78)" field in refund invoices.
In the library version 3, I found an analog of this field. This is the "[PreviousInvoiceId](https://github.com/recurly/recurly-client-net/blob/master/Recurly/Resources/Invoice.cs#L92)". But this field is always null.

I thought that the problem was in mapping, but looking at the response of the server, I saw that the field was really null.

This field is very important to me. Can I count on correcting this behavior? Are there any other ways to find out for which invoice a refund is made?

Thanks a lot for your work!

I'm using version 3.1.0 of the library from [NuGet](https://www.nuget.org/packages/Recurly/).
Environment: .NET Core 2.2
Language version: C# 7.3

**Comment by bhelx** [comment] 2019-11-22 16:43
Thanks @oktaras, We will take a look.

**Comment by bhelx** [comment] 2019-11-22 17:35
@oktaras I took a quick look at this. The behavior should be the same as V2 and you are looking at the correct field. I can't say why it's null without looking deeper into your data server side. I don't think this is an issue with the dotnet client though, and may point to an issue on the server. Would you mind filing an official support ticket? We can leave this issue open and you can reference it in the ticket.

**Comment by taras-oksenchuk-limestone** [comment] 2019-11-22 22:07
@bhelx Thanks for the info and quick response. I created a support ticket and attached a link to this issue. I will expect an answer from them.

**Comment by oktaras** [comment] 2019-11-22 22:08
@bhelx Thanks for the info and quick response. I created a support request and attached a link to this issue. I will expect an answer from them.

**Comment by bhelx** [comment] 2019-11-22 22:45
Thanks @oktaras . I'll ping them on my side!

**Comment by bhelx** [comment] 2020-03-22 20:41
Closing this for the time being since we did not reproduce. Feel free to re-open if there is a problem that can be addressed in this library.

**Closed by bhelx** 2020-03-22 20:41 UTC
Labels: V3, bug?
